version: '3.7'

networks:
  integrations:
    ipam:
      driver: default

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ADMINSERVER_ENABLED: "true"
    healthcheck:
      test: [ "CMD", "nc", "-zv", "127.0.0.1", "2181" ]
      interval: 120s
      timeout: 10s
      retries: 5
    ports:
      - 2181:2181
    networks:
      integrations:


  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - 9093:9093
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-zv", "127.0.0.1", "9092" ]
      interval: 120s
      timeout: 10s
      retries: 5
    networks:
      integrations:

  producer:
    container_name: producer
    hostname: producer
    build:
      context: https://github.com/bry-git/SampleKafkaProducer.git#main
      dockerfile: Dockerfile
      args:
        BOOTSTRAP_SERVER: "kafka:9092"
        KAFKA_TOPIC: "primary"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8088:8088
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 30
        gradle bootrun
    networks:
      integrations: